name: Coverage Comment

on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v8
        with:
          name: coverage-artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Get PR number
        id: pr
        run: echo "number=$(cat pr_number.txt)" >> $GITHUB_OUTPUT

      - name: Post coverage comment
        uses: MishaKav/pytest-coverage-comment@v1.7.2
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          issue-number: ${{ steps.pr.outputs.number }}
